apiVersion: v1
kind: Pod
metadata:
  name: flink-pod
  labels:
    app: flink-pod
spec:
  containers:
    - name: flink-custom
      image: flink-custom
      command: [ "/bin/bash" ]
      imagePullPolicy: IfNotPresent
      stdin: true
      tty: true
    - name: minio-custom
      image: minio-custom
      args: [ "server", "/data", "--console-address", ":9001" ]
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  serviceAccountName: flink-service-account

---

kind: Service
apiVersion: v1
metadata:
  name: flink-service
spec:
  selector:
    app: flink-pod
  ports:
    - port: 9000 # Default port for image